# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resources\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 843)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.qframe_widget = QtWidgets.QFrame(self.centralwidget)
        self.qframe_widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                         "border: 2px solid black;\n"
                                         "border-radius: 6px;")
        self.qframe_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qframe_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qframe_widget.setObjectName("qframe_widget")
        self.gridLayout.addWidget(self.qframe_widget, 0, 1, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setStyleSheet("background-color: rgb(173, 221, 230);\n"
                                    "border: 2px solid black;\n"
                                    "border-radius: 6px;\n"
                                    "")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.combo_options = QtWidgets.QComboBox(self.groupBox)
        self.combo_options.setGeometry(QtCore.QRect(9, 40, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_options.sizePolicy().hasHeightForWidth())
        self.combo_options.setSizePolicy(sizePolicy)
        self.combo_options.setMinimumSize(QtCore.QSize(0, 0))
        self.combo_options.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                         "border: 2px solid black;\n"
                                         "border-radius: 6px;")
        self.combo_options.setObjectName("combo_options")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.btn_choose_folder = QtWidgets.QPushButton(self.groupBox)
        self.btn_choose_folder.setGeometry(QtCore.QRect(140, 40, 101, 31))
        self.btn_choose_folder.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_choose_folder.setStyleSheet("QPushButton {\n"
                                             "            background-color: rgb(255, 255, 255); \n"
                                             "        }\n"
                                             "QPushButton:pressed {\n"
                                             "            background-color: rgb(127, 127, 127);\n"
                                             "        }")
        self.btn_choose_folder.setObjectName("btn_choose_folder")
        self.qtext_folder_path = QtWidgets.QTextEdit(self.groupBox)
        self.qtext_folder_path.setGeometry(QtCore.QRect(10, 80, 231, 51))
        self.qtext_folder_path.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                             "border: 2px solid black;\n"
                                             "border-radius: 6px;")
        self.qtext_folder_path.setObjectName("qtext_folder_path")
        self.frame_config = QtWidgets.QFrame(self.groupBox)
        self.frame_config.setGeometry(QtCore.QRect(0, 150, 251, 341))
        self.frame_config.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_config.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_config.setObjectName("frame_config")
        self.label = QtWidgets.QLabel(self.frame_config)
        self.label.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "border: 2px solid black;\n"
                                 "border-radius: 6px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_config)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 31))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border: 2px solid black;\n"
                                   "border-radius: 6px;")
        self.label_2.setObjectName("label_2")
        self.txt_clear_border = QtWidgets.QTextEdit(self.frame_config)
        self.txt_clear_border.setGeometry(QtCore.QRect(150, 50, 91, 31))
        self.txt_clear_border.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                            "border: 2px solid black;\n"
                                            "border-radius: 6px;")
        self.txt_clear_border.setObjectName("txt_clear_border")
        self.label_3 = QtWidgets.QLabel(self.frame_config)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 111, 31))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border: 2px solid black;\n"
                                   "border-radius: 6px;")
        self.label_3.setObjectName("label_3")
        self.txt_psm = QtWidgets.QTextEdit(self.frame_config)
        self.txt_psm.setGeometry(QtCore.QRect(150, 90, 91, 31))
        self.txt_psm.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border: 2px solid black;\n"
                                   "border-radius: 6px;")
        self.txt_psm.setObjectName("txt_psm")
        self.label_4 = QtWidgets.QLabel(self.frame_config)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border: 2px solid black;\n"
                                   "border-radius: 6px;")
        self.label_4.setObjectName("label_4")
        self.cb_algorithm = QtWidgets.QComboBox(self.frame_config)
        self.cb_algorithm.setGeometry(QtCore.QRect(150, 130, 91, 31))
        self.cb_algorithm.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "border: 2px solid black;\n"
                                        "border-radius: 6px;")
        self.cb_algorithm.setObjectName("cb_algorithm")
        self.cb_algorithm.addItem("")
        self.cb_algorithm.addItem("")
        self.cb_algorithm.addItem("")
        self.label_5 = QtWidgets.QLabel(self.frame_config)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 111, 31))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border: 2px solid black;\n"
                                   "border-radius: 6px;")
        self.label_5.setObjectName("label_5")
        self.cb_morphology = QtWidgets.QComboBox(self.frame_config)
        self.cb_morphology.setGeometry(QtCore.QRect(150, 170, 91, 31))
        self.cb_morphology.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                         "border: 2px solid black;\n"
                                         "border-radius: 6px;")
        self.cb_morphology.setObjectName("cb_morphology")
        self.cb_morphology.addItem("")
        self.cb_morphology.addItem("")
        self.btn_load_model = QtWidgets.QPushButton(self.frame_config)
        self.btn_load_model.setGeometry(QtCore.QRect(10, 210, 231, 31))
        self.btn_load_model.setStyleSheet("QPushButton {\n"
                                          "            background-color: rgb(255, 255, 255); \n"
                                          "        }\n"
                                          "QPushButton:pressed {\n"
                                          "            background-color: rgb(127, 127, 127);\n"
                                          "        }")
        self.btn_load_model.setObjectName("btn_load_model")
        self.btn_start = QtWidgets.QPushButton(self.frame_config)
        self.btn_start.setGeometry(QtCore.QRect(10, 260, 93, 28))
        self.btn_start.setStyleSheet("QPushButton {\n"
                                     "            background-color: rgb(255, 255, 255); \n"
                                     "        }\n"
                                     "QPushButton:pressed {\n"
                                     "            background-color: rgb(127, 127, 127);\n"
                                     "        }")
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtWidgets.QPushButton(self.frame_config)
        self.btn_stop.setGeometry(QtCore.QRect(150, 260, 93, 28))
        self.btn_stop.setStyleSheet("QPushButton {\n"
                                    "            background-color: rgb(255, 255, 255); \n"
                                    "        }\n"
                                    "QPushButton:pressed {\n"
                                    "            background-color: rgb(127, 127, 127);\n"
                                    "        }")
        self.btn_stop.setObjectName("btn_stop")
        self.btn_start_log = QtWidgets.QPushButton(self.groupBox)
        self.btn_start_log.setGeometry(QtCore.QRect(20, 110, 221, 31))
        self.btn_start_log.setStyleSheet("QPushButton {\n"
                                         "            background-color: rgb(255, 255, 255); \n"
                                         "        }\n"
                                         "QPushButton:pressed {\n"
                                         "            background-color: rgb(127, 127, 127);\n"
                                         "        }")
        self.btn_start_log.setObjectName("btn_start_log")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1051, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.combo_options.setItemText(0, _translate("MainWindow", "Image"))
        self.combo_options.setItemText(1, _translate("MainWindow", "Video"))
        self.combo_options.setItemText(2, _translate("MainWindow", "Log"))
        self.btn_choose_folder.setText(_translate("MainWindow", "Choose Folder"))
        self.qtext_folder_path.setHtml(_translate("MainWindow",
                                                  "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                  "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                  "p, li { white-space: pre-wrap; }\n"
                                                  "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                  "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.AppleSystemUIFont\'; font-size:13pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Config Model"))
        self.label_2.setText(_translate("MainWindow", "clear border:"))
        self.txt_clear_border.setText("-1")

        self.label_3.setText(_translate("MainWindow", "PSM:"))
        self.txt_psm.setText("7")

        self.label_4.setText(_translate("MainWindow", "algorithm:"))
        self.cb_algorithm.setItemText(0, _translate("MainWindow", "SobelANPR"))
        self.cb_algorithm.setItemText(1, _translate("MainWindow", "CannyANPR"))
        self.cb_algorithm.setItemText(2, _translate("MainWindow", "EdgelessANPR"))
        self.label_5.setText(_translate("MainWindow", "morphology:"))
        self.cb_morphology.setItemText(0, _translate("MainWindow", "bh"))
        self.cb_morphology.setItemText(1, _translate("MainWindow", "th"))
        self.btn_load_model.setText(_translate("MainWindow", "Load Model"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_start_log.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
