# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resources\ui\widget_video.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetVideo(object):
    def setupUi(self, WidgetVideo):
        WidgetVideo.setObjectName("WidgetVideo")
        WidgetVideo.resize(1123, 692)
        self.gridLayout = QtWidgets.QGridLayout(WidgetVideo)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(WidgetVideo)
        self.groupBox_2.setStyleSheet("background-color: rgb(173, 221, 230);\n"
"border-radius: 6px;\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.qlabel_result = QtWidgets.QLabel(self.groupBox_2)
        self.qlabel_result.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 6px;\n"
"border-radius: 6px;")
        self.qlabel_result.setObjectName("qlabel_result")
        self.gridLayout_2.addWidget(self.qlabel_result, 0, 1, 1, 1)
        self.qlabel_frame = QtWidgets.QLabel(self.groupBox_2)
        self.qlabel_frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 6px;\n"
"border-radius: 6px;")
        self.qlabel_frame.setObjectName("qlabel_frame")
        self.gridLayout_2.addWidget(self.qlabel_frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(WidgetVideo)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet("background-color: rgb(173, 221, 230);\n"
"border: 2px solid black;\n"
"border-radius: 6px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(100, 30))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 3, 1, 1)
        self.btn_capture = QtWidgets.QPushButton(self.frame)
        self.btn_capture.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_capture.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.btn_capture.setObjectName("btn_capture")
        self.gridLayout_3.addWidget(self.btn_capture, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(WidgetVideo)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_3.setStyleSheet("background-color: rgb(173, 221, 230);\n"
"border: 2px solid black;\n"
"border-radius: 6px;\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.qlabel_plate_reco = QtWidgets.QLabel(self.groupBox_3)
        self.qlabel_plate_reco.setGeometry(QtCore.QRect(210, 60, 201, 31))
        self.qlabel_plate_reco.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.qlabel_plate_reco.setAlignment(QtCore.Qt.AlignCenter)
        self.qlabel_plate_reco.setObjectName("qlabel_plate_reco")
        self.qlabel_crop_frame = QtWidgets.QLabel(self.groupBox_3)
        self.qlabel_crop_frame.setGeometry(QtCore.QRect(10, 20, 180, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_crop_frame.sizePolicy().hasHeightForWidth())
        self.qlabel_crop_frame.setSizePolicy(sizePolicy)
        self.qlabel_crop_frame.setMaximumSize(QtCore.QSize(180, 180))
        self.qlabel_crop_frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: 6px;")
        self.qlabel_crop_frame.setText("")
        self.qlabel_crop_frame.setObjectName("qlabel_crop_frame")
        self.btn_view_log = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_view_log.setGeometry(QtCore.QRect(210, 100, 201, 31))
        self.btn_view_log.setStyleSheet("QPushButton {\n"
"            background-color: rgb(255, 255, 255); \n"
"        }\n"
"QPushButton:pressed {\n"
"            background-color: rgb(127, 127, 127);\n"
"        }")
        self.btn_view_log.setObjectName("btn_view_log")
        self.qlabel_date_time = QtWidgets.QLabel(self.groupBox_3)
        self.qlabel_date_time.setGeometry(QtCore.QRect(210, 20, 201, 31))
        self.qlabel_date_time.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.qlabel_date_time.setAlignment(QtCore.Qt.AlignCenter)
        self.qlabel_date_time.setObjectName("qlabel_date_time")
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)

        self.retranslateUi(WidgetVideo)
        QtCore.QMetaObject.connectSlotsByName(WidgetVideo)

    def retranslateUi(self, WidgetVideo):
        _translate = QtCore.QCoreApplication.translate
        WidgetVideo.setWindowTitle(_translate("WidgetVideo", "Form"))
        self.qlabel_result.setText(_translate("WidgetVideo", "TextLabel"))
        self.qlabel_frame.setText(_translate("WidgetVideo", "TextLabel"))
        self.label.setText(_translate("WidgetVideo", "Result"))
        self.btn_capture.setText(_translate("WidgetVideo", "Capture"))
        self.qlabel_plate_reco.setText(_translate("WidgetVideo", "Plate Recognize:"))
        self.btn_view_log.setText(_translate("WidgetVideo", "View log"))
        self.qlabel_date_time.setText(_translate("WidgetVideo", "Time:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetVideo = QtWidgets.QWidget()
    ui = Ui_WidgetVideo()
    ui.setupUi(WidgetVideo)
    WidgetVideo.show()
    sys.exit(app.exec_())
